
import { ProofType, SocialProofItem } from './types';

export const MOCK_PROOF: SocialProofItem[] = [
  {
    id: '1',
    type: ProofType.TWITTER,
    user: {
      name: 'Ankit Mishra',
      handle: '@ankit_tech',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
      isVerified: true,
    },
    content: "My FlexyPe Apex Sneakers just arrived and wow. The weight-to-support ratio is actually insane. Feels like walking on clouds but with better grip. 👟💨 #FlexyPe #PerformanceGear",
    timestamp: '2h ago',
    sourceUrl: 'https://twitter.com',
    tags: ['ApexSneakers', 'Fitness'],
  },
  {
    id: '2',
    type: ProofType.INSTAGRAM,
    user: {
      name: 'Sahil Chaudhary',
      handle: 's_chaudhary_vlogs',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Marcus',
    },
    content: "Early morning session in the new FlexyPe Kinetic Hoodie. The moisture-wicking is the real deal. Best gym fit I've owned so far. 🔥",
    imageUrl: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&q=80&w=800',
    timestamp: '5h ago',
    sourceUrl: 'https://instagram.com',
    tags: ['KineticSeries', 'GymLife'],
  },
  {
    id: '3',
    type: ProofType.VIDEO,
    user: {
      name: 'Babul Singh',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Babul',
    },
    content: "Unboxing the FlexyPe Elite Pack. The packaging alone feels premium. Wait until you see the hidden pockets on this jacket! 🎒",
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800',
    videoUrl: '#',
    timestamp: '1d ago',
    sourceUrl: 'https://tiktok.com',
    tags: ['Unboxing', 'ElitePack'],
  },
  {
    id: '4',
    type: ProofType.REVIEW,
    user: {
      name: 'Priyanka Kaur',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priyanka',
    },
    rating: 5,
    content: "I've been wearing the FlexyPe compression gear for my marathon training. No chafing, perfect fit, and they actually look stylish. Highly recommend to any serious runner.",
    timestamp: 'Oct 12, 2024',
    sourceUrl: 'https://trustpilot.com',
    tags: ['VerifiedPurchase', 'MarathonTraining'],
  },
  {
    id: '5',
    type: ProofType.TESTIMONIAL,
    user: {
      name: 'Aayushi Singh',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aayushi',
      isVerified: true,
    },
    content: "FlexyPe customer service is elite. Had an issue with sizing, and they sent out a replacement before I even dropped the return at the post office. 10/10 experience.",
    timestamp: '3d ago',
    sourceUrl: '#',
    tags: ['CustomerSupport', 'TopTier'],
  },
  {
    id: '6',
    type: ProofType.TWITTER,
    user: {
      name: 'Smriti rani',
      handle: '@jsmith_dev',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Smriti',
    },
    content: "Finally a brand that understands tall athletes. The FlexyPe 'Long' sizes are actually long enough. No more unintentional midriffs! 🙌",
    timestamp: '1w ago',
    sourceUrl: 'https://twitter.com',
    tags: ['Inclusivity', 'Athleisure'],
  },
  {
    id: '7',
    type: ProofType.INSTAGRAM,
    user: {
      name: 'Hariom Singh',
      handle: 'chloe_creates',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Hariom',
    },
    content: "Sunday reset in my FlexyPe Zenith Lounge Set. Sustainable fabrics that feel like silk. Sustainable fashion never felt so good. 🌿✨",
    imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=800',
    timestamp: '2w ago',
    sourceUrl: 'https://instagram.com',
    tags: ['SustainableFashion', 'ZenithSeries'],
  },
  {
    id: '8',
    type: ProofType.REVIEW,
    user: {
      name: 'Ketan Verma',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ketan',
    },
    rating: 4,
    content: "The FlexyPe Resistance bands are much sturdier than the ones I bought on Amazon. A bit more expensive but definitely worth the investment for the home gym.",
    timestamp: 'Nov 5, 2024',
    sourceUrl: 'https://google.com',
    tags: ['HomeGym', 'QualityOverQuantity'],
  },
  {
    id: '9',
    type: ProofType.TWITTER,
    user: {
      name: 'Tannu mishra',
      handle: '@lisaray_yoga',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tannu',
    },
    content: "FlexyPe yoga mats are grippy enough for hot yoga but soft enough for restorative. Game changer. 🧘‍♀️ #FlexyPeYoga",
    timestamp: '12h ago',
    sourceUrl: 'https://twitter.com',
    tags: ['Yoga', 'FlexyPeLife'],
  },
  {
    id: '10',
    type: ProofType.INSTAGRAM,
    user: {
      name: 'Manish Singh',
      handle: 'tommy_v',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Manish',
    },
    content: "Peak summer vibes with my FlexyPe polarized shades. Lightweight and actually stay on while running. 😎",
    imageUrl: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&q=80&w=800',
    timestamp: '1d ago',
    sourceUrl: 'https://instagram.com',
    tags: ['Outdoor', 'Accessories'],
  },
  {
    id: '11',
    type: ProofType.VIDEO,
    user: {
      name: 'Snesha Sharma',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sneha',
    },
    content: "Testing the durability of FlexyPe trail runners in the Alps. Spoiler: they survived without a scratch. 🏔️",
    imageUrl: 'https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&q=80&w=800',
    videoUrl: '#',
    timestamp: '2d ago',
    sourceUrl: 'https://youtube.com',
    tags: ['Adventure', 'Hiking'],
  },
  {
    id: '12',
    type: ProofType.REVIEW,
    user: {
      name: 'Robin Singh',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Robin',
    },
    rating: 5,
    content: "I use the FlexyPe weighted vest for my daily training. The distribution of weight is the best I've encountered. No shoulder pain after long sessions.",
    timestamp: 'Dec 1, 2024',
    sourceUrl: 'https://google.com',
    tags: ['Crossfit', 'Training'],
  },
  {
    id: '13',
    type: ProofType.TESTIMONIAL,
    user: {
      name: 'Vanshika Gupta',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Vanshika',
    },
    content: "Switching all my athletic gear to FlexyPe was the best decision for my performance stats this year. Everything is just so consistent.",
    timestamp: '1mo ago',
    sourceUrl: '#',
    tags: ['ProAthlete', 'Consistency'],
  },
  {
    id: '14',
    type: ProofType.VIDEO,
    user: {
      name: 'Mohan Patel',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mohan',
    },
    content: "FlexyPe hoodie is officially the softest thing I own. I'm living in this now. 🔥✨",
    imageUrl: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=800',
    videoUrl: '#',
    timestamp: '4h ago',
    sourceUrl: 'https://tiktok.com',
    tags: ['Lifestyle', 'Cozy'],
  },
];
